/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/glb/furnitur.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/furnitur.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3DModel'].geometry} material={materials['3DModel']} position={[-7.117, 0, -5.583]} rotation={[1.571, -0.005, 0.199]} scale={0.759} />
      <mesh geometry={nodes['3DModel001'].geometry} material={materials['3DModel']} position={[-7.883, 0, -2.155]} rotation={[1.57, -0.005, 0.026]} scale={0.759} />
      <mesh geometry={nodes['3DModel002'].geometry} material={materials['3DModel']} position={[-2.274, 0, -5.85]} rotation={[1.571, -0.005, 0.199]} scale={0.759} />
      <mesh geometry={nodes['3DModel003'].geometry} material={materials['3DModel']} position={[2.184, 0, -3.452]} rotation={[1.571, -0.005, 0.199]} scale={0.759} />
      <mesh geometry={nodes['3DModel005'].geometry} material={materials['3DModel']} position={[2.23, 1.735, -4.473]} rotation={[1.571, -0.005, 0.277]} scale={0.759} />
      <mesh geometry={nodes['3DModel007'].geometry} material={materials['3DModel']} position={[2.184, 0, -5.886]} rotation={[1.571, -0.005, 0.199]} scale={0.759} />
      <mesh geometry={nodes['3DModel008'].geometry} material={materials['3DModel']} position={[7.249, 1.253, -4.229]} rotation={[3.117, 0.666, 0.214]} scale={0.759} />
      <mesh geometry={nodes['3DModel009'].geometry} material={materials['3DModel']} position={[10.279, 1.253, -4.259]} rotation={[3.107, 0.99, 0.228]} scale={0.759} />
      <mesh geometry={nodes['3DModel006'].geometry} material={materials['3DModel']} position={[-8.364, 0.929, -1.131]} rotation={[2.043, -0.08, -1.526]} scale={0.759} />
      <mesh geometry={nodes['3DModel004'].geometry} material={materials['3DModel']} position={[-3.178, 0, 4.315]} rotation={[1.571, -0.005, 0.199]} scale={0.759} />
    </group>
  )
}

useGLTF.preload('/furnitur.glb')
